  version: 2
  updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"