name: Branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build toUUID
        run: mvn clean install
      - name: Test kotlin-demo
        run: |
          cd demo/kotlin-demo
          mvn test
      - name: Test java-demo
        run: |
          cd demo/java-demo
          mvn test
