name: Branch CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15', '16' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build toUUID
        run: mvn clean install

      - name: Test kotlin-demo
        run: |
          cd demo/kotlin-demo
          mvn test

      - name: Test java-demo
        run: |
          cd demo/java-demo
          mvn test
