name: Main CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15', '16' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build toUUID
        run: mvn clean install

      - name: Test kotlin-demo
        run: |
          cd demo/kotlin-demo
          mvn test

      - name: Test java-demo
        run: |
          cd demo/java-demo
          mvn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Running tests
        run: mvn clean install

      - name: Release snapshot
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg_passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}