name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Running tests
        run: mvn test
      - name: Test kotlin-demo
        run: |
          cd demo/kotlin-demo
          mvn test
      - name: Test java-demo
        run: |
          cd demo/java-demo
          mvn test
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
