name: Release
on:
  release:
    types: [ created ]

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15', '16' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build toUUID
        run: mvn clean install

      - name: Test kotlin-demo
        run: |
          cd demo/kotlin-demo
          mvn test

      - name: Test java-demo
        run: |
          cd demo/java-demo
          mvn test


  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Running tests
        run: mvn clean install

      - name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg_passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}